openapi: 3.0.3
info:
  title: Koa Crud Backend
  description: Koa Crud Backend
  version: 1.0.0
servers:
  - url: https://github.com/daniloab/koa-crud-backend
    description: Production server
security:
  - AppID: []
paths:
  "/api/user/{id}":
    get:
      tags:
        - users
      summary: Get one user
      parameters:
        - name: id
          in: path
          description: platform ID or email
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The user retrieve using the given ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  user:
                    type: object
                    $ref: "#/components/schemas/User"
        "400":
          description: An error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  user:
                    type: object
                    $ref: "#/components/schemas/User"
components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        email:
          type: string
        removedAt:
          type: string
    UserPayload:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        email:
          type: string
        removedAt:
          type: string
tags: []
